steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: '/frontend'
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
  dir: '/frontend'
- name: 'gcr.io/elated-bebop-154812/firebase'
  args: [ 'deploy', '--project', 'elated-bebop-154812', '--token', '${_FIREBASE_TOKEN}']
  dir: '/frontend'
images:
- 'gcr.io/elated-bebop-154812/firebase'